import Footer from '@/components/Footer';
import Header from '@/components/Header';
import Providers from '@/components/Providers';
import { Toaster } from '@/components/ui/Toast';
import { cn } from '@/lib/utils';
import Headerr from '@/components/Headerr';
import '@/styles/globals.css';
import { Inter } from "next/font/google";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={cn("bg-white text-slate-900", inter.className)}>
      <body className="min-h-screen bg-slate-50 dark:bg-slate-900">
        <Providers>
          <Header />
          {children}
          <Toaster position='bottom-right'/>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
